// <auto-generated />
namespace CBTWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class model_refactoring_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(model_refactoring_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201908271728394_model_refactoring_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
